export const ProductsData = [
    {
       productimg:"/demo-main.jpg" 
    },
    {
       productimg:"/demo-dark.jpg" 
    },
    {
       productimg:"/demo-main.jpg" 
    },
     {
       productimg:"/demo-main.jpg" 
    },
    {
       productimg:"/demo-dark.jpg" 
    },
    {
       productimg:"/demo-main.jpg" 
    },
]